
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 12
#define YY_END_OF_BUFFER 13
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[112] =
    {   0,
        0,    0,   13,   11,   12,   12,   11,   11,    6,    3,
       11,    8,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,    2,    0,    0,    0,    0,    7,    0,    0,
        0,   10,    9,    9,    8,    0,    4,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    1,    2,    2,    2,
        2,    0,    0,    0,    0,    0,    0,    0,    0,   10,
        9,    0,    9,    1,    0,    0,    0,    0,    0,    0,
        0,    0,    2,    2,    2,    2,    2,    0,    0,    5,
        5,    5,    0,    0,    5,    5,    5,    5,    0,    0,
        0,    0,    0,    2,    2,    2,    2,    2,    2,    0,

        0,    0,    0,    2,    2,    0,    2,    0,    2,    2,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    5,    6,    1,    1,    7,
        8,    6,    9,   10,    9,   11,    6,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,    1,
       15,    1,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   16,   16,   25,   26,   27,   16,   28,
       16,   29,   30,   16,   16,   16,   16,   16,   31,   16,
       32,    1,   33,    1,    1,    1,   34,   35,   35,   36,

       37,   35,   35,   35,   38,   35,   35,   39,   35,   40,
       41,   35,   35,   42,   43,   44,   45,   35,   35,   35,
       35,   46,   47,   48,   49,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[123] =
    {   0,
        0,    0,  319,   31,   32,  320,   48,   49,   40,   52,
       58,   68,   71,   72,   80,   83,   96,  100,  109,  112,
       84,  113,  124,  294,  295,   34,  312,  320,   59,   89,
       58,    0,  129,  132,  142,  133,  320,  276,  278,  276,
      268,  272,  264,  272,  266,  273,  266,    0,  281,  282,
       85,  282,  277,  277,  276,  136,   56,  151,  152,    0,
      147,  287,  286,  320,  260,  254,  258,  250,  250,  253,
      245,  195,    0,  166,  158,  184,  158,    0,    0,  320,
        0,    0,  176,  174,  173,  320,  170,  169,  132,  127,
      128,  127,  121,    0,  233,    0,    0,    0,    0,  130,

      122,  120,  118,    0,    0,  124,    0,   86,    0,  320,
      320,  282,  124,  285,  122,  288,  291,  110,   98,   97,
       66,   50
    } ;

static const flex_int16_t yy_def[123] =
    {   0,
      111,    1,  111,  111,  111,  111,  112,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  113,  111,  111,  111,  112,  111,  112,  112,
      112,  114,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  115,  115,  115,
      115,  111,  111,  116,  116,  112,  112,  117,  117,  114,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  118,  118,  118,  111,   76,  116,  116,  111,
      116,  116,  117,  117,  112,  111,  117,  117,  111,  111,
      111,  111,  111,  119,  111,   95,  119,   95,   95,  111,

      111,  111,  111,  120,  120,  111,  121,  111,  122,  111,
        0,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111
    } ;

static const flex_int16_t yy_nxt[370] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   10,    9,   10,
       11,   12,   13,   10,    4,    4,   14,   15,    4,   16,
       17,    4,   18,    4,    4,   19,    4,   20,   21,   22,
        4,   10,   10,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   10,    4,   10,   24,
       24,   28,  110,   32,   25,   25,   26,   26,   24,   28,
       54,   28,   28,   25,   55,   26,   29,   24,  109,   33,
       24,   30,   25,   31,   26,   25,   24,   26,   34,   35,
       84,   25,   56,   26,   58,   37,   24,   36,   59,   24,
       24,   25,   28,   26,   25,   25,   26,   26,   24,  107,

      104,   24,   24,   25,   36,   26,   25,   25,   26,   26,
       57,   76,   94,   39,   24,   77,   38,   40,   24,   25,
       46,   26,   41,   25,   73,   26,   48,   24,   64,   42,
       24,   24,   25,   43,   26,   25,   25,   26,   26,   28,
       33,   62,   49,   61,   63,   45,   44,   50,   36,   51,
       47,   36,   34,   35,   86,   86,   83,  108,   61,  106,
       64,   36,   64,   64,  103,   36,   36,   64,   36,  102,
      101,  100,   86,   86,   87,   88,   28,   86,   36,   86,
       62,   99,   96,   36,   80,   80,   95,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   97,

       97,   97,   97,   97,   97,   97,   97,   98,   97,   97,
       97,   97,   97,   97,   97,   80,   80,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       80,   80,   80,   80,   80,   64,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,   80,   80,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,   80,
       80,   80,   27,   64,   27,   60,   64,   60,   80,   93,
       80,   85,   92,   85,   91,   90,   89,   63,   63,   82,

       81,   79,   78,   75,   74,   72,   71,   70,   69,   64,
       68,   67,   66,   65,   64,   28,   53,   52,  111,    3,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111
    } ;

static const flex_int16_t yy_chk[370] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        5,    7,  122,    8,    4,    5,    4,    5,    9,   57,
       26,   31,   29,    9,   26,    9,    7,    8,  121,   11,
       10,    7,    8,    7,    8,   10,   11,   10,   12,   12,
       57,   11,   29,   11,   31,   13,   12,   12,   31,   13,
       14,   12,   30,   12,   13,   14,   13,   14,   15,  120,

      119,   16,   21,   15,   12,   15,   16,   21,   16,   21,
       30,   51,  118,   15,   17,   51,   14,   15,   18,   17,
       21,   17,   16,   18,  115,   18,  113,   19,  108,   17,
       20,   22,   19,   18,   19,   20,   22,   20,   22,   56,
       33,   36,   23,   34,   36,   20,   19,   23,   33,   23,
       22,   34,   35,   35,   58,   59,   56,  106,   61,  103,
      102,   35,  101,  100,   93,   33,   61,   92,   34,   91,
       90,   89,   88,   87,   58,   59,   85,   84,   35,   83,
       36,   77,   75,   61,   76,   76,   74,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,

       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   95,   95,   72,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,  112,   71,  112,  114,   70,  114,  116,   69,
      116,  117,   68,  117,   67,   66,   65,   63,   62,   55,

       54,   53,   52,   50,   49,   47,   46,   45,   44,   43,
       42,   41,   40,   39,   38,   27,   25,   24,    3,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "compilador.l"
#line 2 "compilador.l"
/*
	Descripcion
	Programa que realiza las tres etapas del proceso de compilación para
	el lenguaje definido en clase Pu+
		* Análisis léxico
		* Análisis sintáctico
		* Análisis semántico
	Además, se agrega un proceso de traducción en donde convierte los operadores
	relacionales a su equivalente en lenguaje C

	Autores
	Guzman Sanchez Jose Emmanuel
	Hernandez Romero Pompeyo

*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

FILE *tblSimbolos;  // 1) Tabla de identificadores (dinamica)
FILE *tblCteCad;	// 6) Tabla de constantes tipo cadena (dinamica)
FILE *elementos;	// Tabla con los tokens generados en el analisis (dinamica)
FILE *salida;		// Archivo de salida con el texto traducido

	// Definimos la estructura en las que guardaremos los valores de
	// las tablas. En este caso se hace uso de una lista simple

typedef struct Elemento
{
    struct Elemento *siguiente; 
    int posicion;
    char *nombre;
    char *tipo;
}Elemento;

typedef struct Tabla
{
	struct Elemento *primero;
	struct Elemento *ultimo;
}Tabla;

Tabla *tokens;
Tabla *simbolos;
Tabla *cadenas;
Tabla *relacional;
Tabla *reservadas;
Tabla *clases;
char  cadAtomos[1000];
//char  cadTokens[1000];
Elemento *cadTokens;
char  c;
char *atr;
int   i=0, j=0;


/*************************************************************/
/******************** Analisis lexico ************************/
/*************************************************************/

int buscar(char *cmpLexico, Tabla *tabla){
	// Funcion que busca si el componente lexico indicado se encuentra
	// dentro de la tabla indicada

	Elemento *actual = tabla->primero;
	while (actual != NULL){

		if (strcmp(actual->nombre, cmpLexico) != 0)
			actual = actual->siguiente;
		else
			return actual->posicion;
	}
	return -1;
}

int mostrarTabla(Tabla *tabla, FILE *archivo){
	//	Funcion para mostrar el contenido de una tabla y escribirla en un archivo

	Elemento *actual = tabla->primero;
	while(actual != NULL){
		printf("%i %s %s\n", actual->posicion,actual->nombre,actual->tipo);
		fprintf(archivo,"%i %s %s\n", actual->posicion,actual->nombre,actual->tipo);
		actual = actual->siguiente;
	}
	return 0;
}

char * convertToStr(int num){
	// Funcion que convierte un entero a cadena

	if (num == 0){return "0";}
	else if(num == 1){return "1";}
	else if(num == 2){return "2";}
	else if(num == 3){return "3";}
	else if(num == 4){return "4";}
	else if(num == 5){return "5";}
	else if(num == 6){return "6";}
	else if(num == 7){return "7";}
	else if(num == 8){return "8";}
	else if(num == 9){return "9";}
	else if(num == 10){return "10";}
	else if(num == 11){return "11";}
	else if(num == 12){return "12";}
	else if(num == 13){return "13";}
	else if(num == 14){return "14";}
	else if(num == 15){return "15";}
}

int convertToInt(char *num){
	// Funcion que convierte una cadena a entero

	if (strcmp(num,"0") == 0){return 0;}
	else if(strcmp(num,"1") == 0){return 1;}
	else if(strcmp(num,"2") == 0){return 2;}
	else if(strcmp(num,"3") == 0){return 3;}
	else if(strcmp(num,"4") == 0){return 4;}
	else if(strcmp(num,"5") == 0){return 5;}
	else if(strcmp(num,"6") == 0){return 6;}
	else if(strcmp(num,"7") == 0){return 7;}
	else if(strcmp(num,"8") == 0){return 8;}
	else if(strcmp(num,"9") == 0){return 9;}
	else if(strcmp(num,"10") == 0){return 10;}
	else if(strcmp(num,"11") == 0){return 11;}
	else if(strcmp(num,"12") == 0){return 12;}
	else if(strcmp(num,"13") == 0){return 13;}
	else if(strcmp(num,"14") == 0){return 14;}
	else if(strcmp(num,"15") == 0){return 15;}
}

int agregarAtomo(int clase, char *valor){
	// Funcion que agregar un atomo a la cadena de atomos

	if (clase == 2 || clase == 3 || clase == 5){
		strcat(cadAtomos, valor);
	}
	else if (clase == 0){
		if(strcmp(valor,"0") == 0){strcat(cadAtomos,"b");}
		else if(strcmp(valor,"1") == 0){strcat(cadAtomos,"c");}
		else if(strcmp(valor,"2") == 0){strcat(cadAtomos,"t");}
		else if(strcmp(valor,"3") == 0){strcat(cadAtomos,"e");}
		else if(strcmp(valor,"4") == 0){strcat(cadAtomos,"f");}
		else if(strcmp(valor,"5") == 0){strcat(cadAtomos,"h");}
		else if(strcmp(valor,"6") == 0){strcat(cadAtomos,"m");}
		else if(strcmp(valor,"7") == 0){strcat(cadAtomos,"p");}
		else if(strcmp(valor,"8") == 0){strcat(cadAtomos,"d");}
		else if(strcmp(valor,"9") == 0){strcat(cadAtomos,"i");}
		else if(strcmp(valor,"10") == 0){strcat(cadAtomos,"o");}
	}
	else if (clase == 1){
		strcat(cadAtomos, "a");
	}
	else if (clase == 4){
		if(strcmp(valor,"0") == 0){strcat(cadAtomos,"!");}
		else if(strcmp(valor,"1") == 0){strcat(cadAtomos,"q");}
		else if(strcmp(valor,"2") == 0){strcat(cadAtomos,"<");}
		else if(strcmp(valor,"3") == 0){strcat(cadAtomos,"l");}
		else if(strcmp(valor,"4") == 0){strcat(cadAtomos,">");}
		else if(strcmp(valor,"5") == 0){strcat(cadAtomos,"g");}
	}
	else if (clase == 6){
		strcat(cadAtomos, "s");
	}
	else if (clase == 7){
		strcat(cadAtomos, "n");
	}
	else if (clase == 8){
		strcat(cadAtomos, "r");
	}

	return 0;
}
	
int pushToTable(char *valor, int clase){
	// Funcion que inserta un componente lexico  (clase,valor)
	// a la tabla de tokens. Ademas, inserta el atomo correspondiente 
	// al componente a la cadena de atomos
	Elemento *aux = (Elemento *)calloc(1,sizeof(Elemento));
	aux->siguiente = NULL;
	aux->posicion = clase;
	aux->tipo = "";

	if(clase == 2 || clase == 5 || clase == 7 || clase == 8){
		aux->nombre = valor;
	}
	else if(clase == 3){
		aux->nombre = "=";
	}
	else if(clase == 0){
		aux->nombre = convertToStr(buscar(valor,reservadas));
	}
	else if(clase == 1){
		aux->nombre = convertToStr(buscar(valor,simbolos));
	}
	else if(clase == 4){
		aux->nombre = convertToStr(buscar(valor,relacional));
	}
	else if(clase == 6){
		aux->nombre = convertToStr(buscar(valor,cadenas));
	}

	if (tokens->primero == NULL){
		tokens->primero = aux;
		tokens->ultimo = aux;
	}
	else{
		tokens->ultimo->siguiente = aux;
		tokens->ultimo = aux;
	}

	agregarAtomo(clase, aux->nombre);
	return 0;
}

int push(char *valor, Tabla *tabla){
	// Funcion que inserta un componente lexico a su correspondiente
	// tabla. Ya sea una cadena, un identificador (tablas dinamicas)
	// O un operador relacional, palabaras reservadas o clase (tablas estaticas)

	Elemento *aux = (Elemento *)calloc(1,sizeof(Elemento));
	aux->nombre = (char *)calloc(strlen(valor),sizeof(char));
	strcpy(aux->nombre,valor);
	aux->siguiente = NULL;
	aux->tipo = "";

	if (tabla->primero == NULL){
		aux->posicion = 0;
		tabla->primero = aux;
		tabla->ultimo = aux;
	}
	else{
		if(buscar(valor, tabla) == -1){
			aux->posicion = tabla->ultimo->posicion+1;
			tabla->ultimo->siguiente = aux;
			tabla->ultimo = aux;
		}
	}
	return 0;
}

int crearTablas (Tabla *res, Tabla *rel, Tabla *clas){
	push("Palabras reservadas",clas);
	push("Identificadores",clas);
	push("Simbolos especiales",clas);
	push("Operador de asignacion",clas);
	push("Operadores relaciones",clas);
	push("Operadores aritmeticos",clas);
	push("Constante cadena",clas);
	push("Constantes numericas enteras",clas);
	push("Constantes numericas reales",clas);
	push("Bul",res);
	push("Cadena",res);
	push("Cierto",res);
	push("Entero",res);
	push("Falso",res);
	push("Haz",res);
	push("Mientras",res);
	push("Para",res);
	push("Real",res);
	push("Si",res);
	push("Sino",res);
	push(".DIF.",rel);
	push(".IGL.",rel);
	push(".MN.",rel);
	push(".MNI.",rel);
	push(".MY.",rel);
	push(".MYI.",rel);

	return 0;
}

/*************************************************************/
/******************** Analisis semántico *********************/
/*************************************************************/

int nextAtrib(){
	cadTokens = cadTokens->siguiente;
	atr = (char *)calloc(strlen(cadTokens->nombre),sizeof(char));
	strcpy(atr,cadTokens->nombre);
	return 0;
}

int TC(){
	fprintf(salida,"%s", atr);
	return 0;
}

int TR(){
	int k, pos = convertToInt(atr);
	Elemento *actual = reservadas->primero;

	for(k=0; k<pos; k++)
		actual = actual->siguiente;

	fprintf(salida," %s ",actual->nombre);
}

int AVT(int t, int p){
	int k=0;
	Elemento *actual = simbolos->primero;
	Elemento *tipo = reservadas->primero;

	for(k=0; k<p; k++)
		actual = actual->siguiente;

	for(k=0; k<t; k++)
		tipo = tipo->siguiente;

	if(strcmp(actual->tipo,"")==0){
		actual->tipo = (char *)calloc(strlen(tipo->nombre),sizeof(char));
		strcpy(actual->tipo, tipo->nombre);
	}
	else{
		printf("\nLa variable '%s' ya ha sido declarada como '%s'\n",actual->nombre,actual->tipo);
	}
	fprintf(salida," %s ",actual->nombre);
	return 0;
}

int TP(){
	int k, pos = convertToInt(atr);
	Elemento *actual = simbolos->primero;
	for(k=0; k<pos; k++)
		actual = actual->siguiente;

	if (!strcmp(actual->tipo,""))
		printf("\nVariable '%s' usada sin ser declarada",actual->nombre);
	fprintf(salida," %s ",actual->nombre);
	return 0;
}

int TS(){
	int k, pos = convertToInt(atr);
	Elemento *actual = cadenas->primero;
	for(k=0; k<pos; k++)
		actual = actual->siguiente;

	fprintf(salida," %s ",actual->nombre);
	return 0;
}

int TOR(){
	int k, pos = convertToInt(atr);
	Elemento *actual = relacional->primero;
	for(k=0; k<pos; k++)
		actual = actual->siguiente;

	switch(actual->posicion){
		case 0:
			fprintf(salida," != ");
			break;
		case 1:
			fprintf(salida," == ");
			break;
		case 2:
			fprintf(salida," < ");
			break;
		case 3:
			fprintf(salida," <= ");
			break;
		case 4:
			fprintf(salida," > ");
			break;
		case 5:
			fprintf(salida," >= ");
			break;
	}
	return 0;
}

/*************************************************************/
/******************** Analisis sintactico ********************/
/*************************************************************/

// Declaramos las siguientes funciones debido a que son llamadas
// antes de ser definidas. Con esto evitamos advertencias en la compilacion
int prodE();
int prodY();
int prodR();
int prodN();


int prodF(){
	if (!strcmp(&c,"(")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
		prodE();

		if (!strcmp(&c,")")){
			TC();
			c = cadAtomos[i++];
			nextAtrib();
		}
		else
			printf("\n%i: Se esperaba ')'\n",i-1);

		return 1;
	}
	else if (!strcmp(&c,"a") || !strcmp(&c,"n") || !strcmp(&c,"r")){
		if (!strcmp(&c,"a"))
			TP();
		else
			TC();
		c = cadAtomos[i++];
		nextAtrib();
		return 1;
	}

	else 
		printf("\n%i: Expresion aritmetica invalida\n",i-1);
}

int prodTP(){
	if (!strcmp(&c,"*") || !strcmp(&c,"/") || !strcmp(&c,"%")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
		prodF();
		prodTP();
		return 1;
	}
	else if (!strcmp(&c,"+")||!strcmp(&c,"-")||!strcmp(&c,";")||!strcmp(&c,")")||!strcmp(&c,"!")||!strcmp(&c,"q")||!strcmp(&c,"<")||!strcmp(&c,"l")||!strcmp(&c,">")||!strcmp(&c,"g")){
		return 1;
	}
	else
		printf("\n%i: Operacion aritmetico-logica invalida\n",i-1);
}

int prodT(){
	if (!strcmp(&c,"(") || !strcmp(&c,"a") || !strcmp(&c,"n") || !strcmp(&c,"r")){
		prodF();
		prodTP();
		return 1;
	}
	else
		printf("\n%i: Se esperaba un identificador o constante numerica\n",i-1);
}

int prodEP(){
	if(!strcmp(&c,"+") || !strcmp(&c,"-")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
		prodT();
		prodEP();
		return 1;
	}
	else if(!strcmp(&c,";")||!strcmp(&c,")")||!strcmp(&c,"!")||!strcmp(&c,"q")||!strcmp(&c,"<")||!strcmp(&c,"l")||!strcmp(&c,">")||!strcmp(&c,"g")){
		return 1;
	}
	else
		printf("\n%i: Operacion aritmetico-logica invalida\n",i-1);
}

int prodE(){
	if (!strcmp(&c,"(") || !strcmp(&c,"a") || !strcmp(&c,"n") || !strcmp(&c,"r")){
		prodT();
		prodEP();
		return 1;
	}
	else
		printf("\n%i: Se esperaba una expresion aritmetica\n",i-1);
}

int prodK(){
	if (!strcmp(&c,"s") || !strcmp(&c,"t") || !strcmp(&c,"f")){ 
		if(!strcmp(&c,"s"))
			TS();
		else
			TR();
		c = cadAtomos[i++];
		nextAtrib();
		return 1;
	}
	else if (!strcmp(&c,"(") || !strcmp(&c,"a") || !strcmp(&c,"n") || !strcmp(&c,"r")){
		prodE();
		return 1;
	}
	else
		printf("\n%i: Valor no valido de asignacion\n",i-1);
}

int prodA(){
	if(!strcmp(&c,"a")){
		TP();
		c = cadAtomos[i++];
		nextAtrib();

		if(!strcmp(&c,"=")){
			TC();
			c = cadAtomos[i++];
			nextAtrib();
		}
		else
			printf("\n%i: Se esperaba operador de asignacion (:=)\n",i-1);

		prodK();
		return 1;
	}
	else
		printf("\n%i: Se esperaba una asignacion\n",i-1);
}

int prodQ(){
	if (!strcmp(&c,"!")||!strcmp(&c,"q")||!strcmp(&c,"<")||!strcmp(&c,"l")||!strcmp(&c,">")||!strcmp(&c,"g")){
		// omitimos prodO porque este condicional garantiza que se lea un operador relacional
		TOR();
		c = cadAtomos[i++];
		nextAtrib();
		prodE();
		return 1;
	}
	else if (!strcmp(&c,";") || !strcmp(&c,")"))
		return 1;
	
	else
		printf("\n%i: Se espera operador relacional'\n",i-1);
}

int prodR(){
	if (!strcmp(&c,"(")||!strcmp(&c,"a")||!strcmp(&c,"n")||!strcmp(&c,"r")){
		prodE();
		prodQ();
		return 1;
	}
	else
		printf("\n%i: Se espera condicion logica\n",i-1);
}

int prodH(){

	if(!strcmp(&c,"h")){
		TR();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba 'Haz'\n",i-1);

	if(!strcmp(&c,"[")){
		TC();
		fprintf(salida,"\n");
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba '['\n",i-1);

	prodY();
	fprintf(salida,"\n");
	if(!strcmp(&c,"]")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba ']'\n",i-1);

	if(!strcmp(&c,"m")){
		TR();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba 'Mientras'\n",i-1);

	if(!strcmp(&c,"(")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba '('\n",i-1);

	prodR();

	if(!strcmp(&c,")")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba ')'\n",i-1);

	if(!strcmp(&c,";")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
		fprintf(salida,"\n");
	}
	else
		printf("\n%i: Se esperaba ';'\n",i-1);

	return 1;
}

int prodM(){

	if(!strcmp(&c,"m")){
		TR();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba 'Mientras'\n",i-1);

	if(!strcmp(&c,"(")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba '('\n",i-1);

	prodR();

	if(!strcmp(&c,")")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba ')'\n",i-1);

	if(!strcmp(&c,"[")){
		TC();
		fprintf(salida,"\n");
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba '['\n",i-1);

	prodY();
	fprintf(salida,"\n");
	if(!strcmp(&c,"]")){
		TC();
		fprintf(salida,"\n");
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba ']'\n",i-1);

	return 1;
}

int prodP(){

	if(!strcmp(&c,"p")){
		TR();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba 'Para'\n",i-1);

	if(!strcmp(&c,"(")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba '('\n",i-1);

	prodA();

	if(!strcmp(&c,";")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba ';'\n",i-1);

	prodR();

	if(!strcmp(&c,";")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba ';'\n",i-1);

	prodA();

	if(!strcmp(&c,")")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba ')'\n",i-1);

	if(!strcmp(&c,"[")){
		TC();
		fprintf(salida,"\n");
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba '['\n",i-1);

	prodY();

	fprintf(salida,"\n");
	if(!strcmp(&c,"]")){
		TC();
		fprintf(salida,"\n");
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba ']'\n",i-1);

	return 1;
}

int prodN(){
	if (!strcmp(&c,"a")||!strcmp(&c,"h")||!strcmp(&c,"m")||!strcmp(&c,"p")||!strcmp(&c,"i")||!strcmp(&c,"]"))
		return 1;

	else if (!strcmp(&c,"o")){
		TR();
		c = cadAtomos[i++];
		nextAtrib();

		if (!strcmp(&c, "[")){
			TC();
			fprintf(salida,"\n");
			c = cadAtomos[i++];
			nextAtrib();
		}
		else
			printf("\n%i Se esperaba '['\n",i-1);

		prodY();
		fprintf(salida,"\n");
		if (!strcmp(&c, "]")){
			TC();
			fprintf(salida,"\n");
			c = cadAtomos[i++];
			nextAtrib();
		}
		else
			printf("\n%i: Se esperaba ']'\n",i-1);

		return 1;
	}
	else
		printf("\n%i: Se espera sentencia de control o estructura 'Sino'\n",i-1);
}

int prodI(){

	if(!strcmp(&c,"i")){
		TR();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba 'Si'\n",i-1);

	if(!strcmp(&c,"(")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba '('\n",i-1);

	prodR();

	if(!strcmp(&c,")")){
		TC();
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba ')'\n",i-1);

	if(!strcmp(&c,"[")){
		TC();
		fprintf(salida,"\n");
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba '['\n",i-1);

	prodY();
	fprintf(salida,"\n");

	if(!strcmp(&c,"]")){
		TC();
		fprintf(salida,"\n");
		c = cadAtomos[i++];
		nextAtrib();
	}
	else
		printf("\n%i: Se esperaba ']'\n",i-1);

	prodN();

	return 1;
}

int prodS(){
	if (!strcmp(&c,"a")){
		prodA();

		if (!strcmp(&c,";")){
			TC();
			fprintf(salida,"\n");
			c = cadAtomos[i++];
			nextAtrib();
		}
		else
			printf("\n%i: Se esperaba (;)\n",i-1);
	}
	else if (!strcmp(&c,"h"))
		prodH();

	else if (!strcmp(&c,"m"))
		prodM();
	
	else if (!strcmp(&c,"p"))
		prodP();

	else if (!strcmp(&c,"i"))
		prodI();
	
	else 
		printf("\n%i: Se esperaba sentencia de control\n",i-1);

	return 1;
}

int prodX(){
	if (!strcmp(&c,"a")||!strcmp(&c,"h")||!strcmp(&c,"m")||!strcmp(&c,"p")||!strcmp(&c,"i")){
		prodY();
		return 1;
	}
	else if (!strcmp(&c,"]"))
		return 1;

	else
		printf("\n%i: Se esperaba estructura de control\n",i-1);
}

int prodY(){
	if (!strcmp(&c,"a")||!strcmp(&c,"h")||!strcmp(&c,"m")||!strcmp(&c,"p")||!strcmp(&c,"i")){
		prodS();
		prodX();
		return 1;
	}
	else
		printf("\n%i: Se esperaba sentencia de control\n", i);
}

int prodV(int t){
	if(!strcmp(&c,",")){
		TC();
		int p;
		c = cadAtomos[i++];
		nextAtrib();
		p = convertToInt(atr);

		if(!strcmp(&c,"a")){
			AVT(t,p);
			c = cadAtomos[i++];
			nextAtrib();
		}
		else{
			printf("\n%i: Se esperaba un identificador\n", i);
			return 0;
		}
		prodV(t);
		return 1;
	}
	else if(!strcmp(&c,";")){
		TC();
		fprintf(salida,"\n");
		c = cadAtomos[i++];
		nextAtrib();
		return 1;
	}
	else
		printf("\n%i: Falta (;)\n", i);
}

int prodD(){
	//ProdJ la omitimos porque ya garantizamos que se lee: b, c, e, d
	TR();
	int t;
	int p;
	t = convertToInt(atr);

	c = cadAtomos[i++];
	nextAtrib();
	p = convertToInt(atr);

	if (!strcmp(&c,"a")){
		AVT(t,p);
		c = cadAtomos[i++];
		nextAtrib();
	}
	else 
		printf("\n%i: Se esperaba un identificador\n",i-1);

	prodV(t);
	return 1;
}

int prodZ(){
	if(!strcmp(&c,"b")||!strcmp(&c,"c")||!strcmp(&c,"e")||!strcmp(&c,"d")){
		prodD();
		prodZ();
		return 1;
	}
	else if (!strcmp(&c,"a")||!strcmp(&c,"h")||!strcmp(&c,"m")||!strcmp(&c,"p")||!strcmp(&c,"i")){
		prodY();
		return 1;
	}
	else if (!strcmp(&c,"]"))
		return 1;

	else
		printf("\n%i: Se esperaba sentencia declarativa o de control\n",i-1);
}

int prodG(){
	if (!strcmp(&c,"[")){
		
		TC();
		fprintf(salida,"\n");
		c = cadAtomos[i++];
		nextAtrib();
		prodZ();

		if (!strcmp(&c,"]")){
			fprintf(salida,"\n");
			TC();
			c = cadAtomos[i++];
		}
		else
			printf("\n%i: Falta ']' para cerrar el programa\n",i-1);
		return 1;
	}
	else
		printf("\n%i: Es necesario iniciar el programa con '['\n",i-1);
}

int anSintactico(){
	
	printf("\n\nIniciando analisis sintactico-semantico");

	cadTokens = (Elemento *)calloc(1,sizeof(Elemento));
	cadTokens = tokens->primero;

	c = cadAtomos[i++];

	atr = (char *)calloc(strlen(cadTokens->nombre),sizeof(char));
	strcpy(atr,cadTokens->nombre);

	prodG();
	if (!strcmp(&c,"$"))
		printf("\nAnalisis sintactico-semantico terminado\n");
	else
		printf("\nAnalisis sintactico-semantico terminado con errores\n");
	
	return 1;
}


#line 1537 "lex.yy.c"
#line 980 "compilador.l"
	// Definimos las expresiones regulares para nuestro analizador
#line 1540 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 994 "compilador.l"


#line 1760 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 112 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 320 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 996 "compilador.l"
{	
					char *cadena = (char *)calloc(1,sizeof(char));
					strcpy(cadena,yytext);
					pushToTable(cadena, 0);
				}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 1001 "compilador.l"
{	
					char *cadena = (char *)calloc(1,sizeof(char));
					strcpy(cadena,yytext);
					push(cadena, simbolos);
					pushToTable(cadena,1);
				}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 1007 "compilador.l"
{	
					char *cadena = (char *)calloc(1,sizeof(char));
					strcpy(cadena,yytext);
					pushToTable(cadena,2);
				}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 1012 "compilador.l"
{	
					char *cadena = (char *)calloc(1,sizeof(char));
					strcpy(cadena,yytext);
					pushToTable(cadena,3);
				}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 1017 "compilador.l"
{	
					char *cadena = (char *)calloc(1,sizeof(char));
					strcpy(cadena,yytext);
					pushToTable(cadena,4);
				}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 1022 "compilador.l"
{	
					char *cadena = (char *)calloc(1,sizeof(char));
					strcpy(cadena,yytext);
					pushToTable(cadena,5);
				}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 1027 "compilador.l"
{	
					char *cadena = (char *)calloc(1,sizeof(char));
					strcpy(cadena,yytext);
					push(cadena,cadenas);
					pushToTable(cadena,6);
				}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 1033 "compilador.l"
{	
					char *cadena = (char *)calloc(1,sizeof(char));
					strcpy(cadena,yytext);
					pushToTable(cadena,7);
				}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 1038 "compilador.l"
{	
					char *cadena = (char *)calloc(1,sizeof(char));
					strcpy(cadena,yytext);
					pushToTable(cadena,8);
				}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 1043 "compilador.l"
printf("\n%s\n", yytext);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 1044 "compilador.l"
printf("\nError: %s\n",yytext);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 1047 "compilador.l"
ECHO;
	YY_BREAK
#line 1915 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 112 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 112 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 111);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 1047 "compilador.l"

int main(int argc, char *argv[])
{	
	//Abrimos los archivos de palabras reservadas y op. relacionales para
	//generar las estructuras que los contengan y poder trabajar con ellas
	
	relacional = (Tabla *)calloc(1,sizeof(Tabla));
	reservadas = (Tabla *)calloc(1,sizeof(Tabla));
	clases = (Tabla *)calloc(1,sizeof(Tabla));
	crearTablas(reservadas,relacional, clases);

	tokens = (Tabla *)calloc(1,sizeof(Tabla));
	simbolos = (Tabla *)calloc(1,sizeof(Tabla));
	cadenas = (Tabla *)calloc(1,sizeof(Tabla));

	// Abrimos el archivo a analizar que es pasado como argumento a la funcion main
	// Abrimos el archivo de salida donde se guardara el texto traducido
	yyin = fopen(argv[1],"r");
	elementos = fopen("tokens.txt", "w+");
	tblSimbolos = fopen("simbolos.txt", "w+");
	tblCteCad = fopen("cadenas.txt", "w+");
	salida = fopen("salida.txt", "w+");
	yylex();

	printf("\nTabla de simbolos\n");
	mostrarTabla(simbolos, tblSimbolos);
	printf("\nTabla de constantes cadenas\n");
	mostrarTabla(cadenas, tblCteCad);
	printf("\nTabla de tokens\n");
	mostrarTabla(tokens, elementos);
	
	// Agregamos el caracter de fin de cadena "$"
	strcat(cadAtomos,"$");

	// Ajustamos el formato de impresion para que sea sencillo apreciar el
	// atomo y su posicion correspondiente
	int j=0;
	printf("\nCadena de atomos\n");
	for (j=0;j<strlen(cadAtomos);j++){
		printf("%c ",*(cadAtomos+j));
		if (j>8)
			printf(" ");
	}
	printf("\n");
	for (j=0; j<strlen(cadAtomos); j++)
		printf("%i ",j+1);

	anSintactico();

	printf("\nTabla de simbolos\n");
	fseek(tblSimbolos,0,SEEK_SET);
	mostrarTabla(simbolos, tblSimbolos);
	
	fclose(elementos);
	fclose(tblSimbolos);
	fclose(tblCteCad);
	fclose(salida);
  	return 0;
}

